### PR TITLE
Register page creation

### PR DESCRIPTION
**Pull request by chayayot123**
Due to technical issue: The react doesn't work on his computer so I have to collaborate on this task, assisting in visual technique for making this page possible with out seeing the actual page.
for further explanation, Mister will continue.

### CODE REVIEW

**Comment by chayayot123** [comment]
image

**Comment by VonKiar** [comment]
Thank you sire for assisting me on my task, we truely did a splendid piece of masterwork while collaborating through our heart's content. It may be looking simple but I ensure to you that we ensure looping is possible, the only concern we have is not the css decorative functions but instead it is that if we can get an user's object to run in our loop feature.
So with that thought in mind, if it comes to devastating coding error in the near future while we work on user's object then we will try our utmost best to resolve this madness eventually.

**Comment by Firstyfirst** [comment]
I pull it and see the code in the file so, javascript is work pretty good. Just add some of css. Then, I will add the filter box (the box that show the date of vaccination) later.

**Comment by Sahanon-P** [comment]
Nice work! I will merge them.

**Pull request merged**
